/*
 * Copyright 2014-2016 CyberVision, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

# ifndef KAA_DEFAULTS_H_
# define KAA_DEFAULTS_H_

/**
 *
 * DO NOT EDIT THIS FILE. IT IS AUTO-GENERATED.
 *
 */

# include "kaa_common.h"

# ifdef __cplusplus
extern "C" {
# endif

# define KAA_BUILD_VERSION             "0.10.0"
# define KAA_BUILD_COMMIT_HASH         ""

# define KAA_SDK_TOKEN                 "lsjv60NoY-Umwy4NwlnlWfZLEPs"

# define KAA_PROFILE_SCHEMA_VERSION    0


# define KAA_SYNC_TIMEOUT               60000L


/**
 * @brief Uses to represent transport-specific connection data to establish
 * connection to Bootstrap servers.
 *
 * @see kaa_transport_protocol_id_t
 * @see kaa_access_point_t
 */
typedef struct {
    kaa_transport_protocol_id_t    protocol_id;
    kaa_access_point_t             access_point;
} kaa_bootstrap_server_connection_data_t;

# define KAA_BOOTSTRAP_ACCESS_POINT_COUNT    2

static const kaa_bootstrap_server_connection_data_t KAA_BOOTSTRAP_ACCESS_POINTS[KAA_BOOTSTRAP_ACCESS_POINT_COUNT] =
{
    {
        { 0xfb9a3cf0, 1 },
        {
            0x929a2016,
            320,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -103 , -125 , -13 , 54 , -42 , -73 , -69 , -31 , -126 , 28 , 93 , 0 , -37 , 121 , 47 , 54 , -69 , 46 , 63 , -23 , -111 , 63 , 72 , -45 , 27 , 15 , -26 , -59 , -43 , -1 , 117 , -84 , -20 , -83 , 30 , 14 , -23 , -4 , 45 , 103 , 88 , 127 , 99 , 5 , 39 , -5 , 42 , 52 , -89 , 56 , 52 , -44 , -118 , 26 , -74 , 22 , -10 , 99 , -29 , 102 , -95 , 69 , -59 , -93 , -53 , 68 , -91 , -102 , -112 , -75 , 13 , -123 , -48 , -94 , -90 , 48 , -91 , -92 , 12 , -112 , -2 , -79 , -121 , -107 , -125 , -100 , -18 , -9 , 10 , -53 , 68 , 11 , -27 , -123 , -27 , -15 , -12 , 69 , -45 , 124 , -6 , 73 , -45 , -75 , 25 , 120 , 78 , 93 , 96 , 58 , -50 , -101 , 47 , 15 , -74 , 72 , 104 , 49 , -7 , 98 , -103 , 92 , 60 , 73 , 119 , -45 , 56 , -71 , -110 , -23 , -123 , -106 , -125 , 71 , 12 , 114 , 26 , -47 , 86 , 119 , -73 , -63 , -28 , -33 , -35 , -44 , -40 , 108 , 35 , 90 , -29 , 79 , 43 , 13 , -64 , -9 , -63 , -100 , -91 , -31 , 10 , 46 , 82 , -93 , -12 , 100 , -112 , 126 , 14 , 60 , 57 , 42 , 125 , 1 , -84 , 113 , 104 , -100 , -111 , -86 , -45 , -75 , -69 , 33 , -59 , -17 , 119 , 127 , 97 , -45 , -27 , 45 , -39 , 120 , 112 , 27 , 34 , -126 , -98 , -67 , 86 , -121 , -15 , -9 , -117 , -8 , -114 , 21 , -101 , -24 , -78 , -72 , 8 , -12 , -6 , 24 , -12 , 93 , -112 , 77 , 108 , -64 , 13 , 0 , 58 , -84 , -26 , -25 , 53 , 98 , -113 , -39 , 49 , 56 , -119 , -82 , 123 , -42 , 16 , 51 , -74 , 46 , 8 , -99 , -110 , -77 , -43 , 23 , 4 , 90 , -64 , -39 , 12 , 82 , 8 , 63 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 14 , 49 , 52 , 57 , 46 , 49 , 51 , 50 , 46 , 49 , 55 , 55 , 46 , 57 , 55 , 0 , 0 , 38 , -95             }
        }
    },
    {
        { 0x56c8ff92, 1 },
        {
            0x929a2016,
            320,
            (char []) {
            0 , 0 , 1 , 38 , 48 , -126 , 1 , 34 , 48 , 13 , 6 , 9 , 42 , -122 , 72 , -122 , -9 , 13 , 1 , 1 , 1 , 5 , 0 , 3 , -126 , 1 , 15 , 0 , 48 , -126 , 1 , 10 , 2 , -126 , 1 , 1 , 0 , -103 , -125 , -13 , 54 , -42 , -73 , -69 , -31 , -126 , 28 , 93 , 0 , -37 , 121 , 47 , 54 , -69 , 46 , 63 , -23 , -111 , 63 , 72 , -45 , 27 , 15 , -26 , -59 , -43 , -1 , 117 , -84 , -20 , -83 , 30 , 14 , -23 , -4 , 45 , 103 , 88 , 127 , 99 , 5 , 39 , -5 , 42 , 52 , -89 , 56 , 52 , -44 , -118 , 26 , -74 , 22 , -10 , 99 , -29 , 102 , -95 , 69 , -59 , -93 , -53 , 68 , -91 , -102 , -112 , -75 , 13 , -123 , -48 , -94 , -90 , 48 , -91 , -92 , 12 , -112 , -2 , -79 , -121 , -107 , -125 , -100 , -18 , -9 , 10 , -53 , 68 , 11 , -27 , -123 , -27 , -15 , -12 , 69 , -45 , 124 , -6 , 73 , -45 , -75 , 25 , 120 , 78 , 93 , 96 , 58 , -50 , -101 , 47 , 15 , -74 , 72 , 104 , 49 , -7 , 98 , -103 , 92 , 60 , 73 , 119 , -45 , 56 , -71 , -110 , -23 , -123 , -106 , -125 , 71 , 12 , 114 , 26 , -47 , 86 , 119 , -73 , -63 , -28 , -33 , -35 , -44 , -40 , 108 , 35 , 90 , -29 , 79 , 43 , 13 , -64 , -9 , -63 , -100 , -91 , -31 , 10 , 46 , 82 , -93 , -12 , 100 , -112 , 126 , 14 , 60 , 57 , 42 , 125 , 1 , -84 , 113 , 104 , -100 , -111 , -86 , -45 , -75 , -69 , 33 , -59 , -17 , 119 , 127 , 97 , -45 , -27 , 45 , -39 , 120 , 112 , 27 , 34 , -126 , -98 , -67 , 86 , -121 , -15 , -9 , -117 , -8 , -114 , 21 , -101 , -24 , -78 , -72 , 8 , -12 , -6 , 24 , -12 , 93 , -112 , 77 , 108 , -64 , 13 , 0 , 58 , -84 , -26 , -25 , 53 , 98 , -113 , -39 , 49 , 56 , -119 , -82 , 123 , -42 , 16 , 51 , -74 , 46 , 8 , -99 , -110 , -77 , -43 , 23 , 4 , 90 , -64 , -39 , 12 , 82 , 8 , 63 , 2 , 3 , 1 , 0 , 1 , 0 , 0 , 0 , 14 , 49 , 52 , 57 , 46 , 49 , 51 , 50 , 46 , 49 , 55 , 55 , 46 , 57 , 55 , 0 , 0 , 38 , -96             }
        }
    }};



# define KAA_CONFIGURATION_DATA_LENGTH    1

static const char KAA_CONFIGURATION_DATA[KAA_CONFIGURATION_DATA_LENGTH] =
{
6 };

# ifdef __cplusplus
} // extern "C"
# endif

# endif /* KAA_DEFAULTS_H_ */

